### ISSUE TITLE
https://rdfier.streamlit.app/ ... aktuell mit Problemen 

### ISSUE THREAD

**Issue by karstenT** [poepperl/rdfier#1]
Hi Luca,

https://rdfier.streamlit.app/ wirft aktuell:
"Oh no.
Error running app. If this keeps happening, please [contact support](https://github.com/poepperl/rdfier/issues/new)."

... aber nicht eilig. Bei mir läuft es ja auch lokal;-)

Grüße
Karsten

**Comment by poepperl** [comment]
Hi Karsten,

die Web-App hat eine falsche Python Version genutzt. Sollte jetzt wieder funktionieren!

Viele Grüße
Luca
